#!/usr/bin/env bash

set -xe

python bin/copy_all_pdf_from_docs.py
python bin/generate_pdf_index.py

bash bin/copy_latex_styles.sh

bash bin/build_cv.sh


git add .
git commit -m "auto_push"
git push
